formatting change in salesforce main.tf

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -24,6 +24,7 @@ on:
                 - account
                 - alignx
                 - authorization
+                - integrations/slack
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -49,44 +50,44 @@ jobs:
       
       
       
-      - name: Terraform Format
-        id: fmt
-        run: |
-          cd ./terrafortesting
-          terraform fmt -check
+      # - name: Terraform Format
+      #   id: fmt
+      #   run: |
+      #     cd ./terrafortesting
+      #     terraform fmt -check
 
-      - name: Terraform Init
-        id: init
-        run: |
-          cd ./terrafortesting
-          terraform init -backend-config="bucket=${{ secrets.STATE_BUCKET_NAME }}" \
-          -backend-config="key=s3backend/${{ github.event.inputs.jobs }}/terraform.tfstate" \
-          -backend-config="region=${{ secrets.AWS_REGION }}" \
-          -backend-config="dynamodb_table=${{ secrets.DYNAMODB_TABLE }}" \
-          -input=false -no-color
+      # - name: Terraform Init
+      #   id: init
+      #   run: |
+      #     cd ./terrafortesting
+      #     terraform init -backend-config="bucket=${{ secrets.STATE_BUCKET_NAME }}" \
+      #     -backend-config="key=s3backend/${{ github.event.inputs.jobs }}/terraform.tfstate" \
+      #     -backend-config="region=${{ secrets.AWS_REGION }}" \
+      #     -backend-config="dynamodb_table=${{ secrets.DYNAMODB_TABLE }}" \
+      #     -input=false -no-color
 
-      # Validate the terraform configuration.
-      - name: Terraform Validate
-        id: validate
-        run: |
-          cd ./terrafortesting 
-          terraform validate -no-color
+      # # Validate the terraform configuration.
+      # - name: Terraform Validate
+      #   id: validate
+      #   run: |
+      #     cd ./terrafortesting 
+      #     terraform validate -no-color
 
-      - name: Terraform Plan
-        id: plan
-        run: |
-          cd ./terrafortesting
-          terraform plan --var="environment=dev" --detailed-exitcode -out=tf.plan 2> /dev/null || ec=$?
-          case $ec in 
-            0) echo "No Changes Found": exit 0;;
-            1) printf '%s/n' "Command exited with non-zero";exit 1;;
-            2) echo "Changes found";
-              echo "Changes are required please contact DevOps Team"
-              exit 1         
-            esac
+      # - name: Terraform Plan
+      #   id: plan
+      #   run: |
+      #     cd ./terrafortesting
+      #     terraform plan --var="environment=dev" --detailed-exitcode -out=tf.plan 2> /dev/null || ec=$?
+      #     case $ec in 
+      #       0) echo "No Changes Found": exit 0;;
+      #       1) printf '%s/n' "Command exited with non-zero";exit 1;;
+      #       2) echo "Changes found";
+      #         echo "Changes are required please contact DevOps Team"
+      #         exit 1         
+      #       esac
 
-      - name: Terraform Apply
-        id: apply
-        run: |
-          cd ./terrafortesting
-          echo "jai jai bajrangbali"
+      # - name: Terraform Apply
+      #   id: apply
+      #   run: |
+      #     cd ./terrafortesting
+      #     echo "jai jai bajrangbali"
